# This file was generated by the {rix} R package v0.11.0 on 2024-09-16
# with following call:
# >rix(r_ver = "20f9370d5f588fb8c72e844c54511cab054b5f40",
#  > r_pkgs = c("shiny",
#  > "shinylive",
#  > "httr2",
#  > "countdown"),
#  > system_pkgs = c("quarto",
#  > "vscodium"),
#  > git_pkgs = NULL,
#  > ide = "radian",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses nixpkgs' revision 20f9370d5f588fb8c72e844c54511cab054b5f40 for reproducibility purposes
# which will install R version latest.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/20f9370d5f588fb8c72e844c54511cab054b5f40.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      countdown
      httr2
      shiny
      xml2
      languageserver
      shinylive;
  };
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      quarto
      R
      vscodium;
  };
 
  wrapped_pkgs = pkgs.radianWrapper.override {
    packages = [  rpkgs  ];
  };
 
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs  system_packages  wrapped_pkgs ];
  
}
